# Generated by Django 5.2.3 on 2025-06-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Название ОП')),
                ('whatwilllearn', models.TextField(verbose_name='Что буду изучать')),
                ('whatlearn', models.TextField(verbose_name='Чему научусь')),
                ('pros', models.TextField(verbose_name='Преимущества программы')),
                ('future', models.TextField(verbose_name='Перспективы после')),
            ],
        ),
    ]
